[package]
name = "rjvm_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
rjvm_reader = { path = "../reader" }
thiserror = "1"
log = "0.4.17"
test-log = "0.2.11"
env_logger = "*"
result = "1.0.0"
typed-arena = "2.0.2"
zip = { version = "0.6.4", features = ["deflate"] }
indexmap = "1.9.2"
bitfield-struct = "0.4.4"
const_format = "0.2.31"