[package]
name = "rjvm_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
bitflags = "1.3"
strum_macros = "0.24"
result = "1.0.0"
log = "0.4.17"
test-log = "0.2.11"
env_logger = "*"
itertools = "0.10.5"
cesu8 = "1.1"
